[2023-02-28 15:14:57,618] {processor.py:162} INFO - Started process (PID=19011) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:14:57,622] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:14:57,626] {logging_mixin.py:109} INFO - [2023-02-28 15:14:57,626] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:14:57,656] {logging_mixin.py:109} INFO - [2023-02-28 15:14:57,651] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:14:57,660] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:14:57,694] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.085 seconds
[2023-02-28 15:15:28,445] {processor.py:162} INFO - Started process (PID=19114) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:15:28,456] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:15:28,460] {logging_mixin.py:109} INFO - [2023-02-28 15:15:28,460] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:15:28,485] {logging_mixin.py:109} INFO - [2023-02-28 15:15:28,479] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:15:28,489] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:15:28,527] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.092 seconds
[2023-02-28 15:15:58,637] {processor.py:162} INFO - Started process (PID=19199) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:15:58,642] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:15:58,645] {logging_mixin.py:109} INFO - [2023-02-28 15:15:58,645] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:15:58,662] {logging_mixin.py:109} INFO - [2023-02-28 15:15:58,657] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:15:58,665] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:15:58,698] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.068 seconds
[2023-02-28 15:16:29,344] {processor.py:162} INFO - Started process (PID=19302) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:16:29,349] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:16:29,352] {logging_mixin.py:109} INFO - [2023-02-28 15:16:29,352] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:16:29,369] {logging_mixin.py:109} INFO - [2023-02-28 15:16:29,364] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:16:29,372] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:16:29,403] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.067 seconds
[2023-02-28 15:17:00,198] {processor.py:162} INFO - Started process (PID=19397) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:17:00,205] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:17:00,208] {logging_mixin.py:109} INFO - [2023-02-28 15:17:00,208] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:17:00,228] {logging_mixin.py:109} INFO - [2023-02-28 15:17:00,221] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:17:00,232] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:17:00,264] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.075 seconds
[2023-02-28 15:17:30,726] {processor.py:162} INFO - Started process (PID=19491) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:17:30,730] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:17:30,733] {logging_mixin.py:109} INFO - [2023-02-28 15:17:30,732] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:17:30,755] {logging_mixin.py:109} INFO - [2023-02-28 15:17:30,745] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:17:30,762] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:17:30,792] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.074 seconds
[2023-02-28 15:18:00,964] {processor.py:162} INFO - Started process (PID=19593) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:18:00,970] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:18:00,974] {logging_mixin.py:109} INFO - [2023-02-28 15:18:00,973] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:18:00,994] {logging_mixin.py:109} INFO - [2023-02-28 15:18:00,988] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:18:01,001] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:18:01,036] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.080 seconds
[2023-02-28 15:18:31,732] {processor.py:162} INFO - Started process (PID=19679) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:18:31,737] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:18:31,740] {logging_mixin.py:109} INFO - [2023-02-28 15:18:31,739] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:18:31,757] {logging_mixin.py:109} INFO - [2023-02-28 15:18:31,752] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:18:31,760] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:18:31,796] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.075 seconds
[2023-02-28 15:19:02,055] {processor.py:162} INFO - Started process (PID=19780) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:19:02,062] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:19:02,068] {logging_mixin.py:109} INFO - [2023-02-28 15:19:02,067] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:19:02,100] {logging_mixin.py:109} INFO - [2023-02-28 15:19:02,091] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:19:02,109] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:19:02,153] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.109 seconds
[2023-02-28 15:19:32,434] {processor.py:162} INFO - Started process (PID=19868) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:19:32,441] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:19:32,444] {logging_mixin.py:109} INFO - [2023-02-28 15:19:32,443] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:19:32,463] {logging_mixin.py:109} INFO - [2023-02-28 15:19:32,457] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:19:32,468] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:19:32,504] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.077 seconds
[2023-02-28 15:20:02,723] {processor.py:162} INFO - Started process (PID=19960) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:20:02,728] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:20:02,732] {logging_mixin.py:109} INFO - [2023-02-28 15:20:02,731] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:20:02,758] {logging_mixin.py:109} INFO - [2023-02-28 15:20:02,750] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:20:02,763] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:20:02,802] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.089 seconds
[2023-02-28 15:20:33,273] {processor.py:162} INFO - Started process (PID=20048) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:20:33,279] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:20:33,283] {logging_mixin.py:109} INFO - [2023-02-28 15:20:33,283] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:20:33,302] {logging_mixin.py:109} INFO - [2023-02-28 15:20:33,296] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:20:33,307] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:20:33,339] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.075 seconds
[2023-02-28 15:21:03,792] {processor.py:162} INFO - Started process (PID=20152) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:21:03,798] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:21:03,801] {logging_mixin.py:109} INFO - [2023-02-28 15:21:03,800] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:21:03,822] {logging_mixin.py:109} INFO - [2023-02-28 15:21:03,815] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:21:03,827] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:21:03,861] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.078 seconds
[2023-02-28 15:21:34,223] {processor.py:162} INFO - Started process (PID=20237) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:21:34,227] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:21:34,230] {logging_mixin.py:109} INFO - [2023-02-28 15:21:34,230] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:21:34,249] {logging_mixin.py:109} INFO - [2023-02-28 15:21:34,242] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:21:34,254] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:21:34,288] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.073 seconds
[2023-02-28 15:22:04,780] {processor.py:162} INFO - Started process (PID=20341) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:22:04,793] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:22:04,800] {logging_mixin.py:109} INFO - [2023-02-28 15:22:04,799] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:22:04,827] {logging_mixin.py:109} INFO - [2023-02-28 15:22:04,821] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:22:04,832] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:22:04,869] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.099 seconds
[2023-02-28 15:22:35,299] {processor.py:162} INFO - Started process (PID=20426) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:22:35,306] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:22:35,310] {logging_mixin.py:109} INFO - [2023-02-28 15:22:35,310] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:22:35,329] {logging_mixin.py:109} INFO - [2023-02-28 15:22:35,323] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:22:35,340] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:22:35,394] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.106 seconds
[2023-02-28 15:23:06,191] {processor.py:162} INFO - Started process (PID=20530) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:23:06,198] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:23:06,202] {logging_mixin.py:109} INFO - [2023-02-28 15:23:06,201] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:23:06,222] {logging_mixin.py:109} INFO - [2023-02-28 15:23:06,215] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:23:06,227] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:23:06,264] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.086 seconds
[2023-02-28 15:23:37,126] {processor.py:162} INFO - Started process (PID=20615) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:23:37,130] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:23:37,133] {logging_mixin.py:109} INFO - [2023-02-28 15:23:37,132] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:23:37,151] {logging_mixin.py:109} INFO - [2023-02-28 15:23:37,145] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:23:37,155] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:23:37,185] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.066 seconds
[2023-02-28 15:24:07,783] {processor.py:162} INFO - Started process (PID=20717) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:24:07,788] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:24:07,791] {logging_mixin.py:109} INFO - [2023-02-28 15:24:07,791] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:24:07,811] {logging_mixin.py:109} INFO - [2023-02-28 15:24:07,805] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:24:07,815] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:24:07,847] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.073 seconds
[2023-02-28 15:24:34,832] {processor.py:162} INFO - Started process (PID=20790) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:24:34,837] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:24:34,840] {logging_mixin.py:109} INFO - [2023-02-28 15:24:34,839] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:24:34,874] {logging_mixin.py:109} INFO - [2023-02-28 15:24:34,867] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:24:34,878] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:24:34,913] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.089 seconds
[2023-02-28 15:25:05,478] {processor.py:162} INFO - Started process (PID=20892) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:25:05,484] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:25:05,488] {logging_mixin.py:109} INFO - [2023-02-28 15:25:05,487] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:25:05,510] {logging_mixin.py:109} INFO - [2023-02-28 15:25:05,503] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:25:05,516] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:25:05,553] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.083 seconds
[2023-02-28 15:25:35,821] {processor.py:162} INFO - Started process (PID=20977) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:25:35,826] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:25:35,829] {logging_mixin.py:109} INFO - [2023-02-28 15:25:35,829] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:25:35,846] {logging_mixin.py:109} INFO - [2023-02-28 15:25:35,841] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:25:35,850] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:25:35,881] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.067 seconds
[2023-02-28 15:26:06,457] {processor.py:162} INFO - Started process (PID=21082) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:26:06,462] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:26:06,466] {logging_mixin.py:109} INFO - [2023-02-28 15:26:06,465] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:26:06,484] {logging_mixin.py:109} INFO - [2023-02-28 15:26:06,479] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:26:06,490] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:26:06,525] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.077 seconds
[2023-02-28 15:26:37,193] {processor.py:162} INFO - Started process (PID=21167) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:26:37,199] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:26:37,202] {logging_mixin.py:109} INFO - [2023-02-28 15:26:37,202] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:26:37,221] {logging_mixin.py:109} INFO - [2023-02-28 15:26:37,215] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:26:37,225] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:26:37,258] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.074 seconds
[2023-02-28 15:27:07,813] {processor.py:162} INFO - Started process (PID=21271) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:27:07,820] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:27:07,823] {logging_mixin.py:109} INFO - [2023-02-28 15:27:07,823] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:27:07,844] {logging_mixin.py:109} INFO - [2023-02-28 15:27:07,838] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:27:07,850] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:27:07,886] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.081 seconds
[2023-02-28 15:27:38,188] {processor.py:162} INFO - Started process (PID=21356) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:27:38,193] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:27:38,196] {logging_mixin.py:109} INFO - [2023-02-28 15:27:38,196] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:27:38,211] {logging_mixin.py:109} INFO - [2023-02-28 15:27:38,207] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:27:38,216] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:27:38,244] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.063 seconds
[2023-02-28 15:28:08,629] {processor.py:162} INFO - Started process (PID=21459) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:28:08,634] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:28:08,637] {logging_mixin.py:109} INFO - [2023-02-28 15:28:08,637] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:28:08,654] {logging_mixin.py:109} INFO - [2023-02-28 15:28:08,648] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:28:08,658] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:28:08,691] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.077 seconds
[2023-02-28 15:28:39,425] {processor.py:162} INFO - Started process (PID=21555) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:28:39,431] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:28:39,436] {logging_mixin.py:109} INFO - [2023-02-28 15:28:39,435] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:28:39,459] {logging_mixin.py:109} INFO - [2023-02-28 15:28:39,452] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:28:39,465] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:28:39,506] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.090 seconds
[2023-02-28 15:29:09,685] {processor.py:162} INFO - Started process (PID=21649) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:29:09,691] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:29:09,694] {logging_mixin.py:109} INFO - [2023-02-28 15:29:09,694] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:29:09,712] {logging_mixin.py:109} INFO - [2023-02-28 15:29:09,707] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:29:09,716] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:29:09,753] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.076 seconds
[2023-02-28 15:29:40,047] {processor.py:162} INFO - Started process (PID=21744) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:29:40,052] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:29:40,057] {logging_mixin.py:109} INFO - [2023-02-28 15:29:40,057] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:29:40,080] {logging_mixin.py:109} INFO - [2023-02-28 15:29:40,073] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:29:40,083] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:29:40,124] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.086 seconds
[2023-02-28 15:30:10,607] {processor.py:162} INFO - Started process (PID=21838) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:30:10,612] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:30:10,615] {logging_mixin.py:109} INFO - [2023-02-28 15:30:10,615] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:30:10,631] {logging_mixin.py:109} INFO - [2023-02-28 15:30:10,626] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:30:10,634] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:30:10,666] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.066 seconds
[2023-02-28 15:30:40,939] {processor.py:162} INFO - Started process (PID=21939) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:30:40,947] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:30:40,952] {logging_mixin.py:109} INFO - [2023-02-28 15:30:40,951] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:30:40,980] {logging_mixin.py:109} INFO - [2023-02-28 15:30:40,973] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:30:40,987] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:30:41,032] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.101 seconds
[2023-02-28 15:31:11,874] {processor.py:162} INFO - Started process (PID=22022) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:31:11,879] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:31:11,883] {logging_mixin.py:109} INFO - [2023-02-28 15:31:11,883] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:31:11,901] {logging_mixin.py:109} INFO - [2023-02-28 15:31:11,895] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:31:11,905] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:31:11,938] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.073 seconds
[2023-02-28 15:31:42,321] {processor.py:162} INFO - Started process (PID=22124) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:31:42,326] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:31:42,331] {logging_mixin.py:109} INFO - [2023-02-28 15:31:42,330] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:31:42,357] {logging_mixin.py:109} INFO - [2023-02-28 15:31:42,348] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:31:42,361] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:31:42,410] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.099 seconds
[2023-02-28 15:32:12,950] {processor.py:162} INFO - Started process (PID=22212) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:32:12,957] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:32:12,962] {logging_mixin.py:109} INFO - [2023-02-28 15:32:12,961] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:32:12,984] {logging_mixin.py:109} INFO - [2023-02-28 15:32:12,978] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:32:12,989] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:32:13,027] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.086 seconds
[2023-02-28 15:32:43,265] {processor.py:162} INFO - Started process (PID=22313) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:32:43,272] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:32:43,276] {logging_mixin.py:109} INFO - [2023-02-28 15:32:43,275] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:32:43,298] {logging_mixin.py:109} INFO - [2023-02-28 15:32:43,291] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:32:43,303] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:32:43,339] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.083 seconds
[2023-02-28 15:33:13,388] {processor.py:162} INFO - Started process (PID=22402) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:33:13,394] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:33:13,398] {logging_mixin.py:109} INFO - [2023-02-28 15:33:13,397] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:33:13,421] {logging_mixin.py:109} INFO - [2023-02-28 15:33:13,414] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:33:13,425] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:33:13,462] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.083 seconds
[2023-02-28 15:33:43,520] {processor.py:162} INFO - Started process (PID=22502) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:33:43,525] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:33:43,529] {logging_mixin.py:109} INFO - [2023-02-28 15:33:43,528] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:33:43,549] {logging_mixin.py:109} INFO - [2023-02-28 15:33:43,543] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:33:43,554] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:33:43,590] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.078 seconds
[2023-02-28 15:33:44,657] {processor.py:162} INFO - Started process (PID=22507) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:33:44,665] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:33:44,669] {logging_mixin.py:109} INFO - [2023-02-28 15:33:44,668] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:33:44,696] {logging_mixin.py:109} INFO - [2023-02-28 15:33:44,691] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:33:44,701] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:33:44,732] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.084 seconds
[2023-02-28 15:34:15,503] {processor.py:162} INFO - Started process (PID=22593) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:34:15,508] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:34:15,511] {logging_mixin.py:109} INFO - [2023-02-28 15:34:15,510] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:34:15,531] {logging_mixin.py:109} INFO - [2023-02-28 15:34:15,526] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:34:15,536] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:34:15,568] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.072 seconds
[2023-02-28 15:52:40,441] {processor.py:162} INFO - Started process (PID=22695) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 15:52:40,453] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 15:52:40,457] {logging_mixin.py:109} INFO - [2023-02-28 15:52:40,456] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:52:40,484] {logging_mixin.py:109} INFO - [2023-02-28 15:52:40,478] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 15:52:40,489] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 15:52:40,529] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.098 seconds
[2023-02-28 17:06:28,346] {processor.py:162} INFO - Started process (PID=22779) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 17:06:28,356] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 17:06:28,360] {logging_mixin.py:109} INFO - [2023-02-28 17:06:28,359] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 17:06:28,393] {logging_mixin.py:109} INFO - [2023-02-28 17:06:28,381] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 17:06:28,400] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 17:06:28,462] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.125 seconds
[2023-02-28 17:54:04,317] {processor.py:162} INFO - Started process (PID=22883) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 17:54:04,326] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 17:54:04,338] {logging_mixin.py:109} INFO - [2023-02-28 17:54:04,336] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 17:54:04,378] {logging_mixin.py:109} INFO - [2023-02-28 17:54:04,365] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 17:54:04,384] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 17:54:04,466] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.179 seconds
[2023-02-28 19:19:10,245] {processor.py:162} INFO - Started process (PID=22968) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 19:19:10,251] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 19:19:10,254] {logging_mixin.py:109} INFO - [2023-02-28 19:19:10,253] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 19:19:10,283] {logging_mixin.py:109} INFO - [2023-02-28 19:19:10,277] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 19:19:10,290] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 19:19:10,347] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.117 seconds
[2023-02-28 20:42:48,395] {processor.py:162} INFO - Started process (PID=23073) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 20:42:48,411] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 20:42:48,420] {logging_mixin.py:109} INFO - [2023-02-28 20:42:48,419] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 20:42:48,462] {logging_mixin.py:109} INFO - [2023-02-28 20:42:48,442] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 20:42:48,470] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 20:42:48,582] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.206 seconds
[2023-02-28 22:06:53,100] {processor.py:162} INFO - Started process (PID=23158) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 22:06:53,105] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 22:06:53,112] {logging_mixin.py:109} INFO - [2023-02-28 22:06:53,112] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 22:06:53,147] {logging_mixin.py:109} INFO - [2023-02-28 22:06:53,134] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 22:06:53,155] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 22:06:53,222] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.140 seconds
[2023-02-28 23:27:27,460] {processor.py:162} INFO - Started process (PID=23263) to work on /opt/airflow/dags/etl_dag.py
[2023-02-28 23:27:27,483] {processor.py:613} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-02-28 23:27:27,508] {logging_mixin.py:109} INFO - [2023-02-28 23:27:27,503] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-02-28 23:27:27,571] {logging_mixin.py:109} INFO - [2023-02-28 23:27:27,552] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator'
[2023-02-28 23:27:27,576] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-02-28 23:27:27,709] {processor.py:170} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.303 seconds
